Remove unused variable
```
/home/chiller/Desktop/git/Craft/src/cube.c:336:5: error: Value stored to 'data' is never read [clang-analyzer-deadcode.DeadStores,-warnings-as-errors]
  336 |     data += n * 24;
      |     ^       ~~~~~~
```